package router

import (
	"encoding/json"
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

var upGrader = websocket.Upgrader{
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

func ping(c *gin.Context) {
	ws, err := upGrader.Upgrade(c.Writer, c.Request, nil)
	if err != nil {
		log.Println(1, err)
		return
	}
	defer ws.Close()
	for {
		//读取ws中的数据
		mt, message, err := ws.ReadMessage()
		if err != nil {
			log.Println(2, err)
			break
		}

		type AutoGenerated struct {
			Type    string `json:"type"`
			RoomNum uint   `json:"roomNum"`
		}
		var a AutoGenerated
		log.Println(string(message)[:4] == "0001")
		err = json.Unmarshal([]byte(string(message)[4:]), &a)
		log.Println(err, a)
		err = ws.WriteMessage(mt, message)
		if err != nil {
			log.Println(3, err)
			break
		}
	}
}

func Run() {
	r := gin.Default()
	r.GET("/ping", ping)
	r.Run(":12345")
}
